export interface DoctorDTO {
    id: number;
    firstName: string;
    lastName: string;
    specialization: string;
}

export interface DoctorDetailsDTO extends DoctorDTO{
    address: string;
}

export type DoctorCreateRequest = {
    firstName: string;
    lastName: string;
    peselNumber: string;
    specialization: DoctorSpecialization | "";
    address: string;
};

// @ts-ignore
export enum DoctorSpecialization {
    ALERGOLOGIA = "ALERGOLOGIA",
    ANESTEZJOLOGIA_I_INTENSYWNA_TERAPIA = "ANESTEZJOLOGIA I INTENSYWNA TERAPIA",
    ANGIOLOGIA = "ANGIOLOGIA",
    AUDIOLOGIA_I_FONIATRIA = "AUDIOLOGIA I FONIATRIA",
    BALNEOLOGIA_I_MEDYCYNA_FIZYKALNA = "BALNEOLOGIA I MEDYCYNA FIZYKALNA",
    CHIRURGIA_DZIECIECA = "CHIRURGIA DZIECIĘCA",
    CHIRURGIA_KLATKI_PIERSIOWEJ = "CHIRURGIA KLATKI PIERSIOWEJ",
    CHIRURGIA_NACZYNIOWA = "CHIRURGIA NACZYNIOWA",
    CHIRURGIA_OGOLNA = "CHIRURGIA OGÓLNA",
    CHIRURGIA_ONKOLOGICZNA = "CHIRURGIA ONKOLOGICZNA",
    CHIRURGIA_PLASTYCZNA = "CHIRURGIA PLASTYCZNA",
    CHIRURGIA_SZCZEKOWO_TWARZOWA = "CHIRURGIA SZCZĘKOWO-TWARZOWA",
    CHOROBY_PLUC = "CHOROBY PŁUC",
    CHOROBY_PLUC_DZIECI = "CHOROBY PŁUC DZIECI",
    CHOROBY_WEWNETRZNE = "CHOROBY WEWNĘTRZNE",
    CHOROBY_ZAKAZNE = "CHOROBY ZAKAŹNE",
    DERMATOLOGIA_I_WENEROLOGIA = "DERMATOLOGIA I WENEROLOGIA",
    DIABETOLOGIA = "DIABETOLOGIA",
    DIAGNOSTYKA_LABORATORYJNA = "DIAGNOSTYKA LABORATORYJNA",
    ENDOKRYNOLOGIA = "ENDOKRYNOLOGIA",
    ENDOKRYNOLOGIA_GINEKOLOGICZNA_I_ROZRODCZOSC = "ENDOKRYNOLOGIA GINEKOLOGICZNA I ROZRODCZOŚĆ",
    ENDOKRYNOLOGIA_I_DIABETOLOGIA_DZIECIECA = "ENDOKRYNOLOGIA I DIABETOLOGIA DZIECIĘCA",
    EPIDEMIOLOGIA = "EPIDEMIOLOGIA",
    FARMAKOLOGIA_KLINICZNA = "FARMAKOLOGIA KLINICZNA",
    GASTROENTEROLOGIA = "GASTROENTEROLOGIA",
    GASTROENTEROLOGIA_DZIECIECA = "GASTROENTEROLOGIA DZIECIĘCA",
    GENETYKA_KLINICZNA = "GENETYKA KLINICZNA",
    GERIATRIA = "GERIATRIA",
    GINEKOLOGIA_ONKOLOGICZNA = "GINEKOLOGIA ONKOLOGICZNA",
    HEMATOLOGIA = "HEMATOLOGIA",
    HIPERTENSJOLOGIA = "HIPERTENSJOLOGIA",
    IMMUNOLOGIA_KLINICZNA = "IMMUNOLOGIA KLINICZNA",
    INTENSYWNA_TERAPIA = "INTENSYWNA TERAPIA",
    KARDIOCHIRURGIA = "KARDIOCHIRURGIA",
    KARDIOLOGIA = "KARDIOLOGIA",
    KARDIOLOGIA_DZIECIECA = "KARDIOLOGIA DZIECIĘCA",
    MEDYCYNA_LOTNICZA = "MEDYCYNA LOTNICZA",
    MEDYCYNA_MORSKA_I_TROPIKALNA = "MEDYCYNA MORSKA I TROPIKALNA",
    MEDYCYNA_NUKLEARNA = "MEDYCYNA NUKLEARNA",
    MEDYCYNA_PALIATYWNA = "MEDYCYNA PALIATYWNA",
    MEDYCYNA_PRACY = "MEDYCYNA PRACY",
    MEDYCYNA_RATUNKOWA = "MEDYCYNA RATUNKOWA",
    MEDYCYNA_RODZINNA = "MEDYCYNA RODZINNA",
    MEDYCYNA_SADOWA = "MEDYCYNA SĄDOWA",
    MEDYCYNA_SPORTOWA = "MEDYCYNA SPORTOWA",
    MIKROBIOLOGIA_LEKARSKA = "MIKROBIOLOGIA LEKARSKA",
    NEFROLOGIA = "NEFROLOGIA",
    NEFROLOGIA_DZIECIECA = "NEFROLOGIA DZIECIĘCA",
    NEONATOLOGIA = "NEONATOLOGIA",
    NEUROCHIRURGIA = "NEUROCHIRURGIA",
    NEUROLOGIA = "NEUROLOGIA",
    NEUROLOGIA_DZIECIECA = "NEUROLOGIA DZIECIĘCA",
    NEUROPATOLOGIA = "NEUROPATOLOGIA",
    OKULISTYKA = "OKULISTYKA",
    ONKOLOGIA_I_HEMATOLOGIA_DZIECIECA = "ONKOLOGIA I HEMATOLOGIA DZIECIĘCA",
    ONKOLOGIA_KLINICZNA = "ONKOLOGIA KLINICZNA",
    ORTOPEDIA_I_TRAUMATOLOGIA_NARZADU_RUCHU = "ORTOPEDIA I TRAUMATOLOGIA NARZĄDU RUCHU",
    OTORYNOLARYNGOLOGIA = "OTORYNOLARYNGOLOGIA",
    OTORYNOLARYNGOLOGIA_DZIECIECA = "OTORYNOLARYNGOLOGIA DZIECIĘCA",
    PATOMORFOLOGIA = "PATOMORFOLOGIA",
    PEDIATRIA = "PEDIATRIA",
    PEDIATRIA_METABOLICZNA = "PEDIATRIA METABOLICZNA",
    PERINATOLOGIA = "PERINATOLOGIA",
    POLOZNICTWO_I_GINEKOLOGIA = "POŁOŻNICTWO I GINEKOLOGIA",
    PSYCHIATRIA = "PSYCHIATRIA",
    PSYCHIATRIA_DZIECI_I_MLODZIEZY = "PSYCHIATRIA DZIECI I MŁODZIEŻY",
    RADIOLOGIA_I_DIAGNOSTYKA_OBRAZOWA = "RADIOLOGIA I DIAGNOSTYKA OBRAZOWA",
    RADIOTERAPIA_ONKOLOGICZNA = "RADIOTERAPIA ONKOLOGICZNA",
    REHABILITACJA_MEDYCZNA = "REHABILITACJA MEDYCZNA",
    REUMATOLOGIA = "REUMATOLOGIA",
    SEKSUOLOGIA = "SEKSUOLOGIA",
    TOKSYKOLOGIA_KLINICZNA = "TOKSYKOLOGIA KLINICZNA",
    TRANSFUZJOLOGIA_KLINICZNA = "TRANSFUZJOLOGIA KLINICZNA",
    TRANSPLANTOLOGIA_KLINICZNA = "TRANSPLANTOLOGIA KLINICZNA",
    UROLOGIA = "UROLOGIA",
    UROLOGIA_DZIECIECA = "UROLOGIA DZIECIĘCA",
    ZDROWIE_PUBLICZNE = "ZDROWIE PUBLICZNE",
};